" 行番号の表示
set number
" タイトルバーにファイル名を表示
set title
set ambiwidth=double
" タブの大きさ
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set nrformats-=octal
set hidden
set history=50
set virtualedit=block
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start
set wildmenu
set paste
" ヤンクしたらクリップボードに貼り付ける
set clipboard=unnamedplus
" マウスを有効化
set mouse=a
